/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

/**
 *
 * @author Raaa
 */
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Koneksi.koneksikedatabase;
        
public class Barang extends javax.swing.JFrame {
    private String sql;
    private PreparedStatement ps = null;
    /**
     * Creates new form Barang
     */
    public Barang() {
        initComponents();
        tampilkanData();
        setLocationRelativeTo(this);
    }
    
private void tampilkanData(){
    try{
        String sql = "SELECT * FROM tbl_barang";
        PreparedStatement ps = null;
        Object [] row = {"Kode Barang","Nama Barang","Satuan","Jenis Barang","Harga Beli","Harga Jual","Stok"};
        DefaultTableModel dtm = new DefaultTableModel(null, row);
            TblBarang.setModel(dtm);
            jScrollPane1.setEnabled(true);
            jScrollPane1.setBorder(null);
            jScrollPane1.setViewportView( TblBarang);
        ResultSet rs = null;
        ps = koneksikedatabase.ambilKoneksiDatabase().prepareStatement(sql);   
        rs = ps.executeQuery();
            while(rs.next()){
                String kodebarang = rs.getString(1);
                String namabarang = rs.getString(2);
                String satuan = rs.getString(3);
                String jenisbarang = rs.getString(4);
                String hargabeli = rs.getString(5);
                String hargajual = rs.getString(6);
                String stok = rs.getString(7);
                
                String [] baris = {kodebarang,namabarang,satuan,jenisbarang,hargabeli,hargajual,stok};
                dtm.addRow(baris);
            }
    } catch (Exception e){}
}

private void Bersih(){
    txtKodeBrg.setText("");
    txtNamaBrg.setText("");
    cboSatuan.setSelectedItem("--Pilih--");
    cboJnsBrg.setSelectedItem("--Pilih--");
    txtHrgBeli.setText("");
    txtHrgJual.setText("");
    txtStok.setText("");
}

private void cariData(){
    try{
        String search = txtCariData.getText();
        String sql = "SELECT * FROM tbl_barang WHERE kdbrg LIKE '%"+search+"%' OR nmbrg like'%"+search+"%'";
        PreparedStatement ps = null;
        Object [] row = {"Kode Barang","Nama Barang","Satuan","Jenis Barang","Harga Beli","Harga Jual","Stok"};
        DefaultTableModel dtm = new DefaultTableModel(null, row);
            TblBarang.setModel(dtm);
            jScrollPane1.setEnabled(true);
            jScrollPane1.setBorder(null);
            jScrollPane1.setViewportView( TblBarang);
        ResultSet rs = null;
        ps = koneksikedatabase.ambilKoneksiDatabase().prepareStatement(sql);   
        rs = ps.executeQuery();
        while(rs.next()){
                String kodebarang = rs.getString(1);
                String namabarang = rs.getString(2);
                String satuan = rs.getString(3);
                String jenisbarang = rs.getString(4);
                String hargabeli = rs.getString(5);
                String hargajual = rs.getString(6);
                String stok = rs.getString(7);
                
                String [] baris = {kodebarang,namabarang,satuan,jenisbarang,hargabeli,hargajual,stok};
                dtm.addRow(baris);
            }
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, "Data yang anda cari tidak dapat ditemukan, " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtKodeBrg = new javax.swing.JTextField();
        txtNamaBrg = new javax.swing.JTextField();
        txtHrgBeli = new javax.swing.JTextField();
        txtHrgJual = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        cboSatuan = new javax.swing.JComboBox<>();
        cboJnsBrg = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtCariData = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCariData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblBarang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Input Data Barang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Stok");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Kode Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nama Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Satuan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Jenis Barang");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Harga Beli");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Harga Jual");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txtKodeBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeBrgActionPerformed(evt);
            }
        });
        getContentPane().add(txtKodeBrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 100, -1));

        txtNamaBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBrgActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaBrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 200, -1));

        txtHrgBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHrgBeliActionPerformed(evt);
            }
        });
        getContentPane().add(txtHrgBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 130, -1));

        txtHrgJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHrgJualActionPerformed(evt);
            }
        });
        getContentPane().add(txtHrgJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 130, -1));
        getContentPane().add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 40, -1));

        cboSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Unit", "Pcs", "Box", "Buah" }));
        getContentPane().add(cboSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 100, -1));

        cboJnsBrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Hardware", "Software", "Asesoris" }));
        getContentPane().add(cboJnsBrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 130, -1));

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 100, 30));

        btnSave.setText("SAVE");
        btnSave.setPreferredSize(new java.awt.Dimension(59, 23));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 80, 30));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, 30));

        btnDelete.setText("DELETE");
        btnDelete.setMaximumSize(new java.awt.Dimension(77, 23));
        btnDelete.setMinimumSize(new java.awt.Dimension(77, 23));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 120, 30));

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 120, 30));

        txtCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariDataActionPerformed(evt);
            }
        });
        txtCariData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariDataKeyPressed(evt);
            }
        });
        getContentPane().add(txtCariData, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 120, -1));

        jLabel9.setText("CARI DATA BARANG");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        btnCariData.setText("CARI");
        btnCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariDataActionPerformed(evt);
            }
        });
        getContentPane().add(btnCariData, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, -1));

        TblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 830, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeBrgActionPerformed

    private void txtNamaBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBrgActionPerformed

    private void txtHrgBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHrgBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHrgBeliActionPerformed

    private void txtHrgJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHrgJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHrgJualActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Bersih();
        tampilkanData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariDataActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int keluar = JOptionPane.showConfirmDialog(null, "Keluar Program? ","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(keluar == JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        PreparedStatement ps = null;
        String sql = "INSERT INTO tbl_barang VALUES(?,?,?,?,?,?,?)";
        try{
            if ((txtKodeBrg.getText().equals(""))
              || (txtNamaBrg.getText().equals(""))
              || (cboSatuan.getSelectedItem().equals("--Pilih--"))
              || (cboJnsBrg.getSelectedItem().equals("--Pilih--"))
              || (txtHrgBeli.getText().equals(""))
              || (txtHrgJual.getText().equals(""))
              || (txtStok.getText().equals("")))
            {
                JOptionPane.showMessageDialog(rootPane,"Lengkapi data dengan benar terlebih dahulu!");
            }
            else{
                ps = Koneksi.koneksikedatabase.ambilKoneksiDatabase().prepareStatement(sql);
                ps.setString(1,txtKodeBrg.getText());
                ps.setString(2,txtNamaBrg.getText());
                ps.setString(3, (String)cboSatuan.getSelectedItem());
                ps.setString(4, (String)cboJnsBrg.getSelectedItem());
                ps.setString(5,txtHrgBeli.getText());
                ps.setString(6,txtHrgJual.getText());
                ps.setString(7,txtStok.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data anda sudah disimpan!");
                tampilkanData();
                Bersih();
            }
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Kode barang ini sudah ada, silakan masukkan kode barang yang baru");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try{
            if ((txtKodeBrg.getText().equals(""))
              || (txtNamaBrg.getText().equals(""))
              || (cboSatuan.getSelectedItem().equals("--Pilih--"))
              || (cboJnsBrg.getSelectedItem().equals("--Pilih--"))
              || (txtHrgBeli.getText().equals(""))
              || (txtHrgJual.getText().equals(""))
              || (txtStok.getText().equals("")))
            {
                JOptionPane.showMessageDialog(rootPane,"Silakan pilih data yang akan di hapus!");
            }
            else{
                sql = "UPDATE tbl_barang SET nmbrg='"+ txtNamaBrg.getText()+
                        "',satuan='"+cboSatuan.getSelectedItem()+
                        "',jnsbrg='"+cboJnsBrg.getSelectedItem()+
                        "',hrgbeli='"+txtHrgBeli.getText()+
                        "',hrgjual='"+txtHrgJual.getText()+
                        "',stok='"+txtStok.getText()+
                        "' WHERE kdbrg='" +txtKodeBrg.getText()+"'";
                ps = koneksikedatabase.ambilKoneksiDatabase().prepareStatement(sql);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data berhasil di edit");
                tampilkanData();
                Bersih();
                
            }
        }catch (Exception e)
        {
            
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            if ((txtKodeBrg.getText().equals(""))
              || (txtNamaBrg.getText().equals(""))
              || (cboSatuan.getSelectedItem().equals("--Pilih--"))
              || (cboJnsBrg.getSelectedItem().equals("--Pilih--"))
              || (txtHrgBeli.getText().equals(""))
              || (txtHrgJual.getText().equals(""))
              || (txtStok.getText().equals("")))
            {
                JOptionPane.showMessageDialog(rootPane,"Silakan pilih data yang akan di edit!");
            }
            else{
                sql = "DELETE FROM tbl_barang WHERE kdbrg='"+txtKodeBrg.getText()+"'";
                ps = koneksikedatabase.ambilKoneksiDatabase().prepareStatement(sql);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Hapus data berhasil");
                tampilkanData();
                Bersih();
            }
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Data gagal di edit"+e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariDataActionPerformed
        cariData();
    }//GEN-LAST:event_btnCariDataActionPerformed

    private void txtCariDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariDataKeyPressed
        cariData();
    }//GEN-LAST:event_txtCariDataKeyPressed

    private void TblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblBarangMouseClicked
        int selectedRow = TblBarang.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)TblBarang.getModel();
        txtKodeBrg.setText(model.getValueAt(selectedRow, 0).toString());
        txtNamaBrg.setText(model.getValueAt(selectedRow, 1).toString());
        cboSatuan.setSelectedItem(model.getValueAt(selectedRow, 2).toString());
        cboJnsBrg.setSelectedItem(model.getValueAt(selectedRow, 3).toString());
        txtHrgBeli.setText(model.getValueAt(selectedRow, 4).toString());
        txtHrgJual.setText(model.getValueAt(selectedRow, 5).toString());
        txtStok.setText(model.getValueAt(selectedRow, 6).toString());
    }//GEN-LAST:event_TblBarangMouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblBarang;
    private javax.swing.JButton btnCariData;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboJnsBrg;
    private javax.swing.JComboBox<String> cboSatuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCariData;
    private javax.swing.JTextField txtHrgBeli;
    private javax.swing.JTextField txtHrgJual;
    private javax.swing.JTextField txtKodeBrg;
    private javax.swing.JTextField txtNamaBrg;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
