/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Koneksi.koneksikedatabase;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Raaa
 */
public class CariDataPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form CariDataPelanggan
     */
    private String sql;
    private PreparedStatement ps = null;
    
    public CariDataPelanggan() {
        initComponents();
        cariData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCariData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Cari Data Pelanggan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        txtCariData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCariData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariDataKeyPressed(evt);
            }
        });
        getContentPane().add(txtCariData, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 190, -1));

        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPelanggan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 590, 210));

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCariDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariDataKeyPressed
        cariData();
    }//GEN-LAST:event_txtCariDataKeyPressed

    private void tblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelangganMouseClicked
        TransaksiPenjualan transaksi = new TransaksiPenjualan();
        int i = tblPelanggan.getSelectedRow();
        TableModel tm = tblPelanggan.getModel();
        
        String kodepel = tm.getValueAt(i, 0).toString();
        String namapel = tm.getValueAt(i, 1).toString();
        String alamat = tm.getValueAt(i, 2).toString();
        String telp = tm.getValueAt(i, 3).toString();
        
        transaksi.txtKodePlg.setText(kodepel);
        transaksi.txtNamaPlg.setText(namapel);
        transaksi.txtAlamat.setText(alamat);
        transaksi.txtTelp.setText(telp);
        
        transaksi.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_tblPelangganMouseClicked

    private void cariData(){
        try{
            String search = txtCariData.getText();
            String sql = "SELECT * FROM tbl_pelanggan WHERE kdpel LIKE '%"+search+"%' OR nmpel like'%"+search+"%'";
            PreparedStatement ps = null;
            Object [] row = {"Kode Pelanggan","Nama Pelanggan","Alamat","Telepon"};
            DefaultTableModel dtm = new DefaultTableModel(null, row);
                tblPelanggan.setModel(dtm);
                jScrollPane1.setEnabled(true);
                jScrollPane1.setBorder(null);
                jScrollPane1.setViewportView( tblPelanggan);
            ResultSet rs = null;
            ps = koneksikedatabase.ambilKoneksiDatabase().prepareStatement(sql);   
            rs = ps.executeQuery();
            while(rs.next()){
                    String kodepelanggan = rs.getString(1);
                    String namapelanggan = rs.getString(2);
                    String alamat = rs.getString(3);
                    String telp = rs.getString(4);

                    String [] baris = {kodepelanggan,namapelanggan,alamat,telp};
                    dtm.addRow(baris);
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Data yang anda cari tidak dapat ditemukan, " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CariDataPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPelanggan;
    private javax.swing.JTextField txtCariData;
    // End of variables declaration//GEN-END:variables
}
