/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Koneksi.koneksikedatabase;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Raaa
 */
public class CariDataBarang extends javax.swing.JFrame {

    /**
     * Creates new form CariDatBarang
     */
    public CariDataBarang() {
        initComponents();
        cariData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCariData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Cari Data Barang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        txtCariData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCariData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariDataKeyPressed(evt);
            }
        });
        getContentPane().add(txtCariData, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 190, -1));

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 590, 190));

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCariDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariDataKeyPressed
        cariData();
    }//GEN-LAST:event_txtCariDataKeyPressed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        TransaksiPenjualan transaksi = new TransaksiPenjualan();
        int i = tblBarang.getSelectedRow();
        TableModel tm = tblBarang.getModel();
        
        String kodebrg = tm.getValueAt(i, 0).toString();
        String namabrg = tm.getValueAt(i, 1).toString();
        String satuan = tm.getValueAt(i, 2).toString();
        String hrgjual = tm.getValueAt(i, 5).toString();
        String stok = tm.getValueAt(i, 6).toString();
        
        transaksi.txtKodeBrg.setText(kodebrg);
        transaksi.txtNamaBrg.setText(namabrg);
        transaksi.txtSatuan.setText(satuan);
        transaksi.txtHrgJual.setText(hrgjual);
        transaksi.txtStok.setText(stok);
        
        transaksi.setVisible(true);
        dispose();
    }//GEN-LAST:event_tblBarangMouseClicked

    private void cariData(){
    try{
        String search = txtCariData.getText();
        String sql = "SELECT * FROM tbl_barang WHERE kdbrg LIKE '%"+search+"%' OR nmbrg like'%"+search+"%'";
        PreparedStatement ps = null;
        Object [] row = {"Kode Barang","Nama Barang","Satuan","Jenis Barang","Harga Beli","Harga Jual","Stok"};
        DefaultTableModel dtm = new DefaultTableModel(null, row);
            tblBarang.setModel(dtm);
            jScrollPane1.setEnabled(true);
            jScrollPane1.setBorder(null);
            jScrollPane1.setViewportView( tblBarang);
        ResultSet rs = null;
        ps = koneksikedatabase.ambilKoneksiDatabase().prepareStatement(sql);   
        rs = ps.executeQuery();
        while(rs.next()){
                String kodebarang = rs.getString(1);
                String namabarang = rs.getString(2);
                String satuan = rs.getString(3);
                String jenisbarang = rs.getString(4);
                String hargabeli = rs.getString(5);
                String hargajual = rs.getString(6);
                String stok = rs.getString(7);
                
                String [] baris = {kodebarang,namabarang,satuan,jenisbarang,hargabeli,hargajual,stok};
                dtm.addRow(baris);
            }
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, "Data yang anda cari tidak dapat ditemukan, " + e.getMessage());
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CariDataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtCariData;
    // End of variables declaration//GEN-END:variables
}
