/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Koneksi.koneksikedatabase;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raaa
 */
public class Pelanggan extends javax.swing.JFrame {
    private String sql;
    private PreparedStatement ps = null;
    /**
     * Creates new form Pelanggan
     */
    public Pelanggan() {
        initComponents();
        tampilkanData();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKodePlg = new javax.swing.JTextField();
        txtNamaPlg = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtCariData = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCariData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Input Data Pelanggan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Kode Pelanggan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nama Pelanggan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Telepon");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtKodePlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodePlgActionPerformed(evt);
            }
        });
        getContentPane().add(txtKodePlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 100, -1));

        txtNamaPlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPlgActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaPlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 200, -1));

        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, -1));

        txtTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 130, -1));

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, 30));

        btnSave.setText("SAVE");
        btnSave.setPreferredSize(new java.awt.Dimension(59, 23));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 60, 30));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, 30));

        btnDelete.setText("DELETE");
        btnDelete.setMaximumSize(new java.awt.Dimension(77, 23));
        btnDelete.setMinimumSize(new java.awt.Dimension(77, 23));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 70, 30));

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 60, 30));

        txtCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariDataActionPerformed(evt);
            }
        });
        txtCariData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariDataKeyPressed(evt);
            }
        });
        getContentPane().add(txtCariData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, -1));

        jLabel9.setText("CARI DATA PELANGGAN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        btnCariData.setText("Cari Data");
        getContentPane().add(btnCariData, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPelanggan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodePlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodePlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodePlgActionPerformed

    private void txtNamaPlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPlgActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Bersih();
        tampilkanData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariDataActionPerformed

    private void tampilkanData(){
        try{
            String sql = "SELECT * FROM tbl_pelanggan";
            PreparedStatement ps = null;
            Object [] row = {"Kode Pelanggan","Nama Pelanggan","Alamat","Telepon"};
            DefaultTableModel dtm = new DefaultTableModel(null, row);
                tblPelanggan.setModel(dtm);
                jScrollPane1.setEnabled(true);
                jScrollPane1.setBorder(null);
                jScrollPane1.setViewportView( tblPelanggan);
            ResultSet rs = null;
            ps = koneksikedatabase.ambilKoneksiDatabase().prepareStatement(sql);   
            rs = ps.executeQuery();
                while(rs.next()){
                    String kodepelanggan = rs.getString(1);
                    String namapelanggan = rs.getString(2);
                    String alamat = rs.getString(3);
                    String telp = rs.getString(4);

                    String [] baris = {kodepelanggan,namapelanggan,alamat,telp};
                    dtm.addRow(baris);
                }
        } catch (Exception e){}
    }
    
    private void Bersih(){
        txtKodePlg.setText("");
        txtNamaPlg.setText("");
        txtAlamat.setText("");
        txtTelp.setText("");
    }
    
    private void cariData(){
        try{
            String search = txtCariData.getText();
            String sql = "SELECT * FROM tbl_pelanggan WHERE kdpel LIKE '%"+search+"%' OR nmpel like'%"+search+"%'";
            PreparedStatement ps = null;
            Object [] row = {"Kode Pelanggan","Nama Pelanggan","Alamat","Telepon"};
            DefaultTableModel dtm = new DefaultTableModel(null, row);
                tblPelanggan.setModel(dtm);
                jScrollPane1.setEnabled(true);
                jScrollPane1.setBorder(null);
                jScrollPane1.setViewportView( tblPelanggan);
            ResultSet rs = null;
            ps = koneksikedatabase.ambilKoneksiDatabase().prepareStatement(sql);   
            rs = ps.executeQuery();
            while(rs.next()){
                    String kodepelanggan = rs.getString(1);
                    String namapelanggan = rs.getString(2);
                    String alamat = rs.getString(3);
                    String telp = rs.getString(4);

                    String [] baris = {kodepelanggan,namapelanggan,alamat,telp};
                    dtm.addRow(baris);
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Data yang anda cari tidak dapat ditemukan, " + e.getMessage());
        }
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        PreparedStatement ps = null;
        String sql = "INSERT INTO tbl_pelanggan VALUES(?,?,?,?)";
        try{
            if ((txtKodePlg.getText().equals(""))
              || (txtNamaPlg.getText().equals(""))
              || (txtAlamat.getText().equals(""))
              || (txtTelp.getText().equals("")))
            {
                JOptionPane.showMessageDialog(rootPane,"Lengkapi data dengan benar terlebih dahulu!");
            }
            else{
                ps = Koneksi.koneksikedatabase.ambilKoneksiDatabase().prepareStatement(sql);
                ps.setString(1,txtKodePlg.getText());
                ps.setString(2,txtNamaPlg.getText());
                ps.setString(3,txtAlamat.getText());
                ps.setString(4,txtTelp.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data anda sudah disimpan!");
                tampilkanData();
                Bersih();
            }
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Kode pelanggan ini sudah ada, silakan masukkan kode pelanggan yang baru" +e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try{
            if ((txtKodePlg.getText().equals(""))
              || (txtNamaPlg.getText().equals(""))
              || (txtAlamat.getText().equals(""))
              || (txtTelp.getText().equals("")))
            {
                JOptionPane.showMessageDialog(rootPane,"Silakan pilih data yang akan di hapus!");
            }
            else{
                sql = "UPDATE tbl_pelanggan SET nmpel='"+ txtNamaPlg.getText()+
                        "',alamat='"+txtAlamat.getText()+
                        "',telp='"+txtTelp.getText()+
                        "' WHERE kdpel='" +txtKodePlg.getText()+"'";
                ps = koneksikedatabase.ambilKoneksiDatabase().prepareStatement(sql);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data berhasil di edit");
                tampilkanData();
                Bersih();
                
            }
        }catch (Exception e)
        {
            
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            if ((txtKodePlg.getText().equals(""))
              || (txtNamaPlg.getText().equals(""))
              || (txtAlamat.getText().equals(""))
              || (txtTelp.getText().equals("")))
            {
                JOptionPane.showMessageDialog(rootPane,"Silakan pilih data yang akan di edit!");
            }
            else{
                sql = "DELETE FROM tbl_pelanggan WHERE kdpel='"+txtKodePlg.getText()+"'";
                ps = koneksikedatabase.ambilKoneksiDatabase().prepareStatement(sql);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Hapus data berhasil");
                tampilkanData();
                Bersih();
            }
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Data gagal di edit"+e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelangganMouseClicked
        int selectedRow = tblPelanggan.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tblPelanggan.getModel();
        txtKodePlg.setText(model.getValueAt(selectedRow, 0).toString());
        txtNamaPlg.setText(model.getValueAt(selectedRow, 1).toString());
        txtAlamat.setText(model.getValueAt(selectedRow, 2).toString());
        txtTelp.setText(model.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_tblPelangganMouseClicked

    private void txtCariDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariDataKeyPressed
        cariData();
    }//GEN-LAST:event_txtCariDataKeyPressed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int keluar = JOptionPane.showConfirmDialog(null, "Keluar Program? ","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(keluar == JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariData;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPelanggan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCariData;
    private javax.swing.JTextField txtKodePlg;
    private javax.swing.JTextField txtNamaPlg;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
